spring:
  application:
    name: VPN services control
  datasource:
    url: jdbc:postgresql:vpnservice
    driver-class-name: org.postgresql.Driver
    username: vpnservice
    password: vpnservice
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8082